StartAt: CreateOrder
States:
  CreateOrder:
    Type: Task
    Resource: ${OrdersFunctionArn}
    Next: UpdateInventory
    Catch:
      - ErrorEquals:
          - States.ALL
        ResultPath: $.error
        Next: CancelOrder
  UpdateInventory:
    Type: Task
    Resource: ${InventoryFunctionArn}
    Next: ProcessPayment
    Catch:
      - ErrorEquals:
          - States.ALL
        ResultPath: $.error
        Next: InventoryRollback
  ProcessPayment:
    Type: Task
    Resource: ${PaymentsFunctionArn}
    Next: Notify
    Catch:
      - ErrorEquals:
          - States.ALL
        ResultPath: $.error
        Next: PaymentRefund
  CancelOrder:
    Type: Task
    Resource: ${OrdersCancelFunctionArn}
    Next: Notify
  InventoryRollback:
    Type: Task
    Resource: ${InventoryRollbackFunctionArn}
    Next: CancelOrder
  PaymentRefund:
    Type: Task
    Resource: ${PaymentsRefundFunctionArn}
    Next: InventoryRollback
  Notify:
    Type: Task
    Resource: ${NotificationsFunctionArn}
    End: true
