StartAt: InvokeOrders
States:
  InvokeOrders:
    Type: Task
    Resource: ${OrdersFunctionArn}
    Next: InvokeInventory
    Catch:
      - ErrorEquals:
          - States.ALL
        ResultPath: $.error
        Next: InvokeOrdersCancel
  InvokeInventory:
    Type: Task
    Resource: ${InventoryFunctionArn}
    Next: InvokePayments
    Catch:
      - ErrorEquals:
          - States.ALL
        ResultPath: $.error
        Next: InvokeInventoryRollback
  InvokePayments:
    Type: Task
    Resource: ${PaymentsFunctionArn}
    Next: InvokeNotifications
    Catch:
      - ErrorEquals:
          - States.ALL
        ResultPath: $.error
        Next: InvokePaymentsRefund
  InvokeNotifications:
    Type: Task
    Resource: ${PaymentsFunctionArn}
    End: true
  InvokeOrdersCancel:
    Type: Task
    Resource: ${OrdersCancelFunctionArn}
    Next: InvokeNotifications
  InvokeInventoryRollback:
    Type: Task
    Resource: ${InventoryRollbackFunctionArn}
    Next: InvokeOrdersCancel
  InvokePaymentsRefund:
    Type: Task
    Resource: ${PaymentsRefundFunctionArn}
    Next: InvokeInventoryRollback
